Not able to build SDK on local
microsoftgraph/msgraph-sdk-dotnet pull request #2553
Opened 2024-06-17 07:05 UTC by MartinM85

Fix for #2452

2024-06-17 12:18 UTC, baywet requested changes

2024-06-17 12:18 UTC, baywet commented on src/Microsoft.Graph/Microsoft.Graph.csproj
> +    <Version>$(VersionPrefix)</Version>
could we add a condition: if the suffix is empty?

2024-06-17 13:30 UTC, baywet approved these changes

2024-06-17 13:30 UTC, baywet commented
@andrueastman for final review and merge

2024-06-18 07:06 UTC, andrueastman commented
We just need to validate the scripts below are not broken by this change.
 
- https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/scripts/IncrementMinorVersion.ps1
- https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/scripts/ValidateUpdatedNugetVersion.ps1

2024-06-18 07:42 UTC, MartinM85 commented
Executed both scripts manually on local...seems like no issues

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/7744844/b48103af-048b-4c9b-aff4-496cebf47144)

2024-06-18 12:57 UTC, baywet approved these changes
Thanks for checking!

2024-06-18 12:57 UTC, merged

2024-06-18 12:58 UTC, baywet commented
@MartinM85 can you replicate those changes on github.com/microsoftgraph/msgraph-beta-sdk-dotnet please?

2024-06-18 13:08 UTC, MartinM85 commented
@baywet [Microsoft.Graph.Beta.csproj](https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/0944ee89ddea63d783b93fdff56b42e1a5f1c1aa/src/Microsoft.Graph/Microsoft.Graph.Beta.csproj#L35) has `VersionSuffix` set to **preview**. NuGet restore works fine from Visual Studio for https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet.

2024-06-18 13:09 UTC, baywet commented
Thanks for double checking, no work required then!